### PR TITLE
Remove AHBL

### PR DESCRIPTION
**Pull request by neuhaus**
AHBL is no longer operational

### CODE REVIEW

**Comment by neuhaus** [comment]
See http://www.ahbl.org/content/changes-ahbl for more information.

**Comment by neuhaus** [comment]
Fixes issue #4

**Comment by DjinnS** [comment]
Hello,

Thank you for this information and this request !

**Comment by DjinnS** [comment]
Because of the previous merge, I make your change manually.

Change is done, so, I close your request.

Thank you again !

**Pull request closed without merging**
